ExpenseReport/config/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
]

ExpenseReport/webapp/urls.py
from django.urls import path

from . import views

app_name='webapp'

urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('top/', views.TopView.as_view(), name='top'),
    path('route/', views.RouteView.as_view(), name='route'),
    path('route/delete/', views.RouteDeleteView.as_view(), name='route_delete'),
    path('route-list/', views.RouteListView.as_view(), name='route_list'),
    path('', views.ExpenseReportView.as_view()),
    path('expense-report/', views.ExpenseReportView.as_view(), name='expense_report'),
]

ExpenseReport/templates/base.html
{% load django_bootstrap5 %}
<html lang="ja">

<head>
  <meta charset="utf-8">
  <title>{% block title %}{% endblock %}</title>
  {% bootstrap_css %}
  {% bootstrap_javascript %}
</head>

<body>
  {% block contents %}{% endblock %}
  {% block extrajs %}{% endblock %}
</body>

</html>

ExpenseReport/templates/expense_report.html
{% extends 'base.html' %}

{% load static %}

{% block title %}清算書{% endblock %}

{% block contents %}
<div>
    {% include 'navigationbar.html' %}
</div>
<div class="container">
    <div class="row">
        <div class="col-2">
            <a href="/expense-report/?date={{ date }}&val=-1">前月</a>
        </div>
        <div class="col-2">
            <h4 >{{ date_month }}</h4>
        </div>
        <div class="col-2">
            <a href="/expense-report/?date={{ date }}&val=1">翌月</a>
        </div>
    </div>
</div>
</div>
<div>
    <a href="{% url 'webapp:route_list' %}">経路一覧</a>
</div>
<table class="table table-striped table-bordered">
    <form action="{% url 'webapp:expense_report' %}" method="post">
        <tr>
            {% for col in header %}
            <th scope="col">
                {{ col }}
            </th>
            {% endfor %}
        </tr>
        {% for form in formset %}
        <tr>
            <div class="col-sm-4">
                {% for field in form %}
                {% csrf_token %}
                <td>
                    {{ field }}
                    {% if field == form.fare %}
                    円
                    {% endif %}
                </td>
                {% endfor %}
            </div>
        </tr>
        {% endfor %}
        {{ formset.management_form }}
        <tr>
            <td><button type="submit" class="btn btn-primary">保存</button></td>
        </tr>
        <tr>
            <td><input type="hidden" name="date" value="{{ date }}" id="date"></td>
        </tr>
    </form>
</table>
{% endblock %}

{% block extrajs %}{% endblock %}

ExpenseReport/templates/login.html
{% extends 'base.html' %}

{% load static %}

{% block title %}{% endblock %}

{% block contents %}
<h2>ログイン</h2>
<form action="{% url 'webapp:login' %}" method="POST">
    {% csrf_token %}
    {{ form.non_field_errors }}
    {% for field in form %}
    {{ field }}
    {{ field.errors }}
    <hr>
    {% endfor %}
    <button type="submit">ログイン</button>
</form>
{% endblock %}
{% block extrajs %}{% endblock %}

ExpenseReport/templates/navigationbar.html
{# ナビゲーションバー#}
<nav class="navbar navbar-dark bg-primary">
    <div class="container-fluid">
        <div>
            <a class="navbar-brand" href="#">
                <i class="bi bi-bootstrap-fill" style="font-size: 2rem;"></i>
            </a>
        </div>
        <div class="flex-grow-1" style="max-width:500px;">

        </div>
        <div class="text-light nav-item dropdown">
            <a class="nav-link dropdown-toggle text-light" href="#" id="navbarDropdown" role="button"
                data-bs-toggle="dropdown" aria-expanded="false">
                {{user.username}}
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="http://127.0.0.1:8000/admin/webapp">管理画面</a></li>
                <li>
                    <hr class="dropdown-divider">
                </li>
                <li><a class="dropdown-item" href="{% url 'webapp:logout' %}">ログアウト</a></li>
            </ul>
        </div>
    </div>
</nav>

ExpenseReport/templates/route_delete_modal.html
<!-- モーダルウィンドウ -->
<div class="modal fade" id="delete_modal" tabindex="-1" aria-labelledby="delete_modal_label" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="delete_modal_label">削除</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                削除しますか？
            </div>
            <div class="modal-footer">
                <form method="post" action="{% url 'webapp:route_delete' %}" >
                    {% csrf_token %}
                    <input type="hidden" class="btn btn-primary" id="delete_route_id" name="delete_route_id" >
                    <input type="submit" class="btn btn-primary" value="削除">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">キャンセル</button>
                </form>
            </div>
        </div>
    </div>
</div>

ExpenseReport/templates/route_input_modal.html
<div class="modal fade" id="input-modal" tabindex="-1" aria-labelledby="input-modal-label" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="input-modal-label">経路</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form method="post" action="{% url 'webapp:route' %}">
                <div class="modal-body" id="modal-body">
                    <table class="table table-striped table-bordered">
                        {% csrf_token %}
                        <tr>
                            <div class="col-sm-4">
                                {{route_form}}
                            </div>
                        </tr>
                    </table>
                </div>
                <div class="modal-footer">
                    <input type="submit" class="btn btn-primary" value="登録">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">キャンセル</button>
                </div>
                <input type="hidden" class="btn btn-primary" id="input_route_id" name="input_route_id" >
            </form>
        </div>
    </div>
</div>

ExpenseReport/templates/route_list.html
{% extends 'base.html' %}

{% load static %}

{% block title %}経路一覧{% endblock %}

{% block contents %}
<div>
    {% include 'navigationbar.html' %}
</div>
<h2>経路一覧</h2>
<div>
    <a href="{% url 'webapp:expense_report' %}">メイン</a>
</div>
<table class="table table-striped table-bordered">
    {% csrf_token %}
    <tr>
        {% for col in header %}
        <th scope="col">
            {{ col }}
        </th>
        {% endfor %}
    </tr>
    {% for route in object_list %}
    <tr>
        <div class="col-sm-4">
            <td>{{ route }}</td>
            <td>{{ route.transportation_id }}</td>
            <td>{{ route.fare }}円 </td>
            <td>
                <button type="button" name="btn_route_update" class="btn btn-primary" data-bs-toggle="modal"
                    data-id="{{ route.pk }}" data-target="{{ route }}" data-departure-point="{{ route.departure_point}}" 
                    data-arrival-point="{{ route.arrival_point}}" data-transportation="{{ route.transportation}}" 
                    data-fare="{{ route.fare }}" data-bs-target="#input-modal" onclick="update_route_bt(event)">
                    更新
                </button>
            </td>
            <td>
                <button type="button" name="btn_route_update" class="btn btn-primary" data-bs-toggle="modal"
                    data-id="{{ route.pk }}" data-target="{{ route }}" data-bs-target="#delete_modal"
                    onclick="delete_route_bt(event)">
                    削除
                </button>
            </td>
        </div>
    </tr>
    {% endfor %}
</table>
<button type="button" name="btn_route_add" class="btn btn-primary" data-bs-toggle="modal" data-target="{{ route }}"
    data-bs-target="#input-modal" onclick="add_route_bt(event)">追加</button>
<!-- モーダルウィンドウ -->
<div>
    {% include 'route_input_modal.html' %}
</div>
<div>
    {% include 'route_delete_modal.html' %}
</div>
{% endblock %}

{% block extrajs %}
<script>
    function add_route_bt(event) {
        document.getElementById("input_route_id").value = 0 ;
        const route_name = event.currentTarget.dataset['target'];
        document.getElementById("input-modal-label").textContent = "経路追加";
    }

    function update_route_bt(event) {
        // 対象のid
        const route_id = event.currentTarget.dataset['id'];
        document.getElementById("input_route_id").value = route_id ;
        // 経路名
        const route_name = event.currentTarget.dataset['target'];
        document.getElementById("input-modal-label").textContent = route_name;
        // 出発地点
        const route_departure_point = event.currentTarget.dataset['departurePoint'];
        document.getElementById("id_departure_point").value = route_departure_point;
        // 到着地点
        const route_arrival_point = event.currentTarget.dataset['arrivalPoint'];
        document.getElementById("id_arrival_point").value = route_arrival_point;
        // 交通機関
        const route_transportation = event.currentTarget.dataset['transportation'];
        document.getElementById("id_transportation").value = route_transportation;
        // 金額
        const route_fare = event.currentTarget.dataset['fare'];
        document.getElementById("id_fare").value = route_fare;
    }

    function delete_route_bt(event) {
        const route_id = event.currentTarget.dataset['id'];
        const route_name = event.currentTarget.dataset['target'];
        document.getElementById("delete_modal_label").textContent = route_name;
        document.getElementById("delete_route_id").value = route_id;
    }
</script>
{% endblock %}

ExpenseReport/templates/route_register.html
{% extends 'base.html' %}

{% load static %}

{% block title %}{% endblock %}

{% block contents %}{% endblock %}

{% block extrajs %}{% endblock %}